BOT_TOKEN = "8389664932:AAHw-vE5o52ODbQgUPcHf5CsSlhAIls_vDE"
BOT_USERNAME = "Sband_Stars_Bot"
FLYER_KEY = "FL-bCNglG-EDVnGx-URelIm-PhGydF"

SUBSCRIBE_REWARD = 0.25
MIN_WITHDRAW = 15.0
DB_URL = "sqlite:///sband_stars.db"
